### ISSUE TITLE
머 안되는거 같은뎅? 

### ISSUE THREAD

**Issue by jjie7704** [msaltnet/tizen-xamarin-app#18]
오른쪽에 뭐가 안보입니다

**Comment by msaltnet** [comment]
뭐가 안보인다는 거에요? Label 같은거?

**Comment by msaltnet** [comment]
제가 추가했는데, 아직 수락을 안하셨네요~ 확인해보셔요~
![image](https://user-images.githubusercontent.com/9311990/92983081-70c28480-f4dc-11ea-9a8c-059800937900.png)
